name: Deploy PR previews

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: deploy-preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      pull-requests: read
   
    steps:
      - name: Checkout
        uses: actions/checkout@v3  #Explicitly checkout the PR
        with:
          ref: ${{ github.event.pull_request.head.sha }} #refs/pull/${{ github.event.number }}/merge
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
  
      - name: Build
        if: github.event.action != 'closed' # Skip the build if the PR has been closed
        run: |
          node tiddlywiki ./tiddlywiki/editions/tw5.com --output ./build --build index

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: master
          deploy-repository: saqimtiaz/test_tiddlywiki.com-gh-pages
          token: ${{ secrets.DEPLOY_PREVIEW }}
